# Generated by Django 2.2.2 on 2019-06-13 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sku',
        ),
    ]
